auth_enabled: false #별도의 인증처리 X

server:
  http_listen_port: 3100 #promtail이나 grafana가 loki와 통신 시 사용하는 포트 번호

common:
  path_prefix: /loki   # 데이터를 컨테이너 내부의 /loki 경로에 저장하도록 설정
  storage:
    filesystem: #저장소로 서버 디스크 사용
      chunks_directory: /loki/chunks #압축된 로그 원본 저장 경로
      rules_directory: /loki/rules #알림 규칙 파일 저장 경로
  replication_factor: 1 #데이터 복제 X
  ring: # Loki를 클러스터로 묶을 때 인식하기 위한 설정
    instance_addr: 127.0.0.1 #단일 인스턴스 환경에서 자기 자신 가르키는 주소
    kvstore:
      store: inmemory #클러스터 상태정보를 메모리에서 관리

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb #최신 TSDB 인덱스 저장방식 사용
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# 15일이 지난 로그는 자동으로 삭제
limits_config:
  retention_period: 360h

# 파일 시스템 사용 시 데이터 압축 및 삭제 담당
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true