groups:
  groupA:
    - githubName: paka-jo
      discordKey: JUNGWON
    - githubName: jaehwannnnnn
      discordKey: JAEHWAN
    - githubName: sseen2
      discordKey: SEEUN

  groupB:
    - githubName: 0-tae
      discordKey: YONGTAE
    - githubName: dotae1
      discordKey: DABIN