package com.samsamhajo.deepground.studyGroup.entity;

public enum TechTag {
  // Frontend
  JAVASCRIPT, TYPESCRIPT, REACT, ANGULAR, NEXT_JS, VUE_JS, TAILWIND, BOOTSTRAP, HTML, CSS, SASS,

  // Backend
  NODE_JS, EXPRESS, NEST_JS, SPRING, DJANGO, FLASK, JAVA, PYTHON, C_SHARP, PHP, GO, RUST, RUBY,

  // Database
  MYSQL, POSTGRESQL, MONGODB, NOSQL, SQL,

  // Cloud & DevOps
  AWS, GCP, AZURE, DOCKER, KUBERNETES, CI_CD, DEVOPS, GIT, GITHUB, GITLAB,

  // Etc
  REST_API, GRAPHQL, TESTING, TDD, DATA_STRUCTURE, ALGORITHM, MACHINE_LEARNING, AI, BLOCKCHAIN,

  // Mobile
  MOBILE, IOS, ANDROID, REACT_NATIVE, FLUTTER
}
