name: Deploy
on:
  push:
    branches: [ "main"]

  workflow_dispatch:

permissions:
  contents: read

env:
  working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # GitHub 저장소 코드 내려받기
      - name: Checkout Repository
        uses: actions/checkout@v3
        # JDK version 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        # Gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create .env for tests
        run: |
          echo "${{ secrets.ENV }}" | base64 -d > .env
          chmod 600 .env

        # 4. 테스트 및 빌드
      - name: Build with Gradle
        run: ./gradlew clean build


        # Docker 빌드를 위한 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 생성 (ARM64)
        run: |
          docker buildx create --use
          docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_REPOSITORY }} --load .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag ${{ secrets.DOCKER_REPOSITORY }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Docker Hub에 Docker 이미지 Push하기
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest


        # OCI에 배포
      - name: Deploy to OCI
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ubuntu
          key: ${{ secrets.OCI_KEY }}
          script: |
            cd /home/ubuntu/studen

            echo "${{ secrets.ENV }}" | base64 -d > .env
            chmod 600 .env # .env 
            
            docker compose down || true
            
            docker compose pull
            docker compose up -d

             sleep 20
            echo "=== Docker Compose 서비스 상태 ==="
            docker ps
            
            echo "=== 컨테이너 로그 확인 ==="
            docker compose logs --tail 30

            rm .env
